receptor =  receptor.pdbqt
ligand =  ligand.pdbqt
tunnel =  tunnel1.dsd

center_x = 2.52133986464
center_y = 65.5242018105
center_z = 67.6543357911
size_x = 29
size_y = 31
size_z = 33

exhaustiveness = 1
cpu = 1
multiple_search = 3
